name: nix-linux

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    - uses: cachix/cachix-action@releases/v6
      with:
        name: hasktorch
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: cachix use iohk
    - run: nix-build
